language: java

matrix:
  include:
  - jdk: openjdk8
  - jdk: openjdk10
  - jdk: openjdk11
  - jdk: openjdk12

install: mvn install

after_success:
  - mvn clean test

cache:
  directories:
    - $HOME/.m2
